### ISSUE TITLE
Los alerts no tienen título

### ISSUE THREAD

**Issue by mauroa** [ThinkUpStudios/osdepym#101]
Por defecto se muestra el título de la página web, lo cual no queda bien. Ver imagen

**Comment by mauroa** [comment]
![image1](https://cloud.githubusercontent.com/assets/2921919/10457249/d8c0ef5a-719b-11e5-85ed-4f6997dcd936.PNG)

**Comment by dariocamarro** [comment]
#109 Ya se subió el ajuste.
Mauro probalo en iOS por favor.

**Comment by mauroa** [comment]
Fixed
