### ISSUE TITLE
El estilo del menu esta roto en iOS

### ISSUE THREAD

**Issue by mauroa** [ThinkUpStudios/osdepym#89]
![image1](https://cloud.githubusercontent.com/assets/2921919/10427787/d403b882-70c2-11e5-8806-f5fe67f3bf48.PNG)

**Comment by fcostazini** [comment]
Ya está identificado. Lo estoy arreglando

**Comment by fcostazini** [comment]
Lo cerré sin querer

**Comment by mauroa** [comment]
Fixed
