### ISSUE TITLE
El estilo de los botones en detalle de prestador esta roto en iOS (verificar en Android)

### ISSUE THREAD

**Issue by mauroa** [ThinkUpStudios/osdepym#90]
![image1 1](https://cloud.githubusercontent.com/assets/2921919/10427822/19c42bcc-70c3-11e5-8045-46b359d04161.PNG)

**Comment by fcostazini** [comment]
Se caga el como llegar :S... debe ser lo mismo de siempre..se pisan los estilos.

**Comment by mauroa** [comment]
Es que le sobra texto. Es muy largo. El botón lo veo bien. Debe tener width fijo.

**Comment by mauroa** [comment]
Fixed
