### ISSUE TITLE
El icono de colapsable en el detalle de prestador no funciona

### ISSUE THREAD

**Issue by mauroa** [ThinkUpStudios/osdepym#92]
Repro:
- Menu > Cartilla Medica
- Buscar por especialidad
- Realizar una búsqueda que tenga datos
- Seleccionar un prestador
- En el detalle, hay un icono de colapsable al lado del Laboratorio, que no funciona

**Comment by fcostazini** [comment]
Si funciona. Tiene que tener varios renglones la especialidad.

**Comment by mauroa** [comment]
En la app original se muestra el icono de collapsable si la especialidad tiene una línea? Si es así lo cerramos como Invalid.
