### ISSUE TITLE
VERIFICAR - El botón de 'Horarios' en detalle de prestador, realiza una llamada

### ISSUE THREAD

**Issue by mauroa** [ThinkUpStudios/osdepym#93]
Repro:

Menu > Cartilla Medica
Buscar por especialidad
Realizar una búsqueda que tenga datos
Seleccionar un prestador
En el detalle, clickear en el botón 'Horarios'

Esto es una funcionalidad esperada? Es confuso querer ver los horarios y que se haga una llamada

**Comment by fcostazini** [comment]
No está implementada la función de horarios

**Comment by mauroa** [comment]
Deberíamos ocultar el botón entonces?

**Comment by dariocamarro** [comment]
Se agregó la funcionalidad.
