### ISSUE TITLE
Se piden coordenadas actuales en la pantalla de resultados

### ISSUE THREAD

**Issue by mauroa** [ThinkUpStudios/osdepym#94]
Repro:

Menu > Cartilla Medica
Buscar por especialidad
Realizar una búsqueda que tenga datos

Resultado actual: En la pantalla de resultados, aparece un popup pidiendo permiso para usar 'my location'.

Resultado esperado: Ese permiso debería pedirse en la pantalla de detalle de prestador, que es donde se usan los mapas. Es molesto que aparezca eso cuando en los resultados no hay mapas. El usuario puede no entender para que se lo piden, hasta la siguiente pantalla.

**Comment by mauroa** [comment]
![image1 2](https://cloud.githubusercontent.com/assets/2921919/10428351/20c731cc-70c7-11e5-9482-afe944e34c95.PNG)

**Comment by dariocamarro** [comment]
Eso esta a propósito. Lo puse ahi para que tarde menos la carga del mapa.
Tarda mucho buscar la ubicación actual.
Si no les parece correcto lo muevo.

**Comment by mauroa** [comment]
No se si incorrecto, raro si. Pero si es por un tema de performance y es muy lento cargarlo en la de detalle, lo dejamos ahí. Yo lo decía por un tema de usabilidad nomas.

**Comment by mauroa** [comment]
Cierro el bug ya que dejamos la funcionalidad como está ahora, por un tema de performance
