### ISSUE TITLE
El botón 'Llamar' en detalle de prestador aparece igual si no hay teléfono

### ISSUE THREAD

**Issue by mauroa** [ThinkUpStudios/osdepym#98]
Resultado actual: Si algún prestador no tiene teléfono, el botón de 'Llamar' aparece igual

Resultado esperado: El botón solo debe aparece si el prestador tiene teléfono

Dato para probar:
Urrere, Carlos Luis
Radriografías, Ecografías y otros estudios

**Comment by fcostazini** [comment]
Ahi lo miro. En otros casos que no le puse telefono, el botón no se muestra.

**Comment by mauroa** [comment]
Fixed
